name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # или master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t bri1545/bri1545:latest .

    - name: Push image to DockerHub
      run: docker push bri1545/bri1545:latest

    - name: SSH and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull bri1545/bri1545:latest
          docker stop app || true && docker rm app || true
          docker run -d --name app -p 80:3000 bri1545/bri1545:latest

